version: '3'
services:
  web:
    build: .
      # context: ./Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ./loginsystem:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laundry_db
      MYSQL_USER: laundry_user
      MYSQL_PASSWORD: laundry_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
